apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 9090  # Exposing the service on port 9090
      targetPort: 9090  # Targeting the container's port 9090
  type: LoadBalancer

